export const challenges = [
  {
    title: 'Qr code component',
    url: '/qr-code-component',
    image: '/qr-code-component/desktop-preview.jpg',
    tag: 'newbie',
    desc: "A perfect first challenge if you're new to HTML and CSS. The card layout doesn't shift, so it's ideal if you haven't learned about building responsive layouts yet.",
    code: 'https://github.com/anbelf7/frontend-mentor/tree/main/pages/qr-code-component',
  },
  {
    title: 'Intro section with dropdown navigation',
    url: '/qr-code-component',
    image: '/qr-code-component/image-qr-code.png',
    tag: 'junior',
    desc: 'This challenge will test your ability to create dropdown navigation menus, a common pattern on larger sites. It will also provide some nice basic layout challenges.',
    code: '',
  },
  {
    title: 'Expenses chart component',
    url: '/qr-code-component',
    image: '/qr-code-component/image-qr-code.png',
    tag: 'junior',
    desc: "In this challenge, you'll create a bar chart component from scratch. We provide a local JSON file, so you can add the chart data dynamically if you choose.",
    code: '',
  },
  {
    title: 'Article preview component',
    url: '/qr-code-component',
    image: '/qr-code-component/image-qr-code.png',
    tag: 'newbie',
    desc: "Practice your layout skills with this article preview component. There's lots of fun to be had playing around with animations for the sharing icons as well.",
    code: '',
  },
  {
    title: 'Manage landing page',
    url: '/qr-code-component',
    image: '/qr-code-component/image-qr-code.png',
    tag: 'intermediate',
    desc: 'This challenge will be a great test for your responsive skills. There are lots of small details and slight content shifts for different screen sizes.',
    code: '',
  },
];
